name: Puppeteer Automation Check

on:
  pull_request:
    paths:
      - '.github/workflows/puppeteer-automation.yml'

jobs:
  test-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: |
          npm init -y
          npm install puppeteer
      
      - name: Validate Puppeteer Installation
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          console.log('Puppeteer installed successfully');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('https://example.com');
            console.log('Browser launched and navigated successfully');
            await browser.close();
          })();"
