name: Update GitHub Profile README

on:
  pull_request:
    branches:
      - main

jobs:
  preview-readme-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub Stats Preview
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jordanpartridge
          show_icons: true
          theme: tokyonight
      
      - name: Show Metrics Configuration
        run: echo "Metrics would be updated in this workflow"
