name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly update
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jordanpartridge
          show_icons: true
          theme: tokyonight
      
      - name: Update Wakatime Stats
        uses: athul/wakatime-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
      
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README metrics" || exit 0
          git push
